server:
  port: 9000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: srm-material-server
          uri: lb://srm-material-server
          predicates:
            - Path=/srm/material/**
        - id: srm-auth-server
          uri: lb://srm-auth-server
          predicates:
            - Path=/srm/auth/**
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: gateway-sever